# Site
repository: sergeyrudik/sr-cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sergei Rudik
title: Senior QA Engineer
email: rudikqa@gmail.com
website: https://sergeyrudik.github.io/sr-cv/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: sergeirudik
github_username:  sergeyrudik
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: sergey.rudik.7
# flickr_username: jekyll
instagram_username: sergeyrudik
linkedin_username: sergei-rudik
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: test
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sergei and I'm a senior QA engineer. I have experience in automating frontend and backend testing in python and js.

  I also mentored students at an online testing school.

  I am most skilled in: <mark>Testing</mark> and <mark>Eating Pizza</mark>

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kaspersky Lab
        link: kaspersky.com
        # link_text: boringcompany.com
        sub_title: Senior QA Engineer
        caption: June 2020 - Present
        quote: >
          Maximum increase in the number of tests.
        description: | # this will include new lines to allow paragraphs
            Automation of test scenarios using pytest (including selenium), support for existing autotests.
            Writing unittests with javascript + jest.
            Manual and automated testing (functional and non-functional, integration).
            Preparation of test plans and test scenarios.

      - layout: left
        title: Delimobil
        link: delimobil.ru
        # link_text: boringcompany.com
        sub_title: QA Engineer
        caption: October 2019 - June 2020
        quote: >
          А lot of API and mobile app checks.
        description: | # this will include new lines to allow paragraphs
            Several mobile applications, many features, active agile testing.
            Automated tests in Python for API/Backend.

      - layout: left
        title: ASOdesk
        link: asodesk.com
        # link_text: boringcompany.com
        sub_title: QA Engineer
        caption: September 2018 - September 2019
        quote: >
          This is a highly loaded web service with a lot of words that help in promoting applications for AppStore and GooglePlay.
        description: | # this will include new lines to allow paragraphs
            There are also various reports and tools to analyze these words.
            Automated tests in Python and Selenium for UI.

      - layout: left
        title: Netcracker Technology
        link: netcracker.com
        # link_text: boringcompany.com
        sub_title: QA Engineer
        caption: September 2017 - September 2018
        quote: >
          Training in all types of testing.
        description: | # this will include new lines to allow paragraphs
            Have worked at highly loaded project for the telecommunication provider of GTD, which includes equipment accounting, phone numbers accounting, connection of various services to subscribers, as well as a variety of operations on customers in the system.
            Manual testing, writing automated tests in Robot framework and internal tools.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PSUTI - Povolzhskiy State University of Telecommunications & Informatics
        caption: 2010 - 2015
        sub_title: Сommunications Engineer
        description: | # this will include new lines to allow paragraphs
          Engineering education in the telecommunications sector.

  - title: A Little Bit More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      My hobbies and interests except of software engineering and networks are:
      - Travels
      - Driving
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
